name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: checkout actions
      uses: actions/checkout@v2
      with:
        repository: vectorscores/actions
        path: actions
    - name: test action
      uses: ./actions
      with:
        package-json-path: "./package.json"
